### ISSUE TITLE
Unable to load DLL 'GameNetworkingSockets'

### ISSUE THREAD

**Issue by Jeroen-VdB** [silentbaws/XLMultiplayer#25]
On a clean Windows Server 2019 I'm unable to start a server v0.9.1 due to the following exception:

> Unhandled Exception:
> Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'GameNetworkingSockets': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
>    at Valve.Sockets.Native.GameNetworkingSockets_Init(IntPtr identity, StringBuilder errorMessage)
>    at Valve.Sockets.Library.Initialize(StringBuilder errorMessage)
>    at Valve.Sockets.Library.Initialize()
>    at XLMultiplayerServer.FileServer.ServerLoop()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: Unable to load DLL 'GameNetworkingSockets': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
>    at Valve.Sockets.Native.GameNetworkingSockets_Init(IntPtr identity, StringBuilder errorMessage)
>    at Valve.Sockets.Library.Initialize(StringBuilder errorMessage)
>    at Valve.Sockets.Library.Initialize()
>    at XLMultiplayerServer.Server.ServerLoop()
>    at System.Threading.Tasks.Task.Execute()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at XLMultiplayerServerConsoleApp.ConsoleServer.Main(String[] args)

Ofcourse the DLL is present, so I'm not sure which dependencies I'm missing.
Doess the GameNetworkingSockets.dll depend on a specific .NET version or Steam software?

**Comment by Jeroen-VdB** [comment]
Found the required dependency: [Visual C++](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads). For my x64 server I downloaded [vc_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe)
