### ISSUE TITLE
Unable to load DLL 'GameNetworkingSockets' on WinServer 2019

### ISSUE THREAD

**Issue by BrynWyn** [silentbaws/XLMultiplayer#31]
When attempting to run XLMultiplayerServerConsoleApp.exe getting the below issue:

Starting server initialization
No maps folder set so using C:\Users\Administrator\Documents\SkaterXL\SkaterXLServer\Maps

WARNING: FAILED TO FIND ANY CUSTOM MAPS IN THE MAPS DIRECTORY ONLY COURTHOUSE AND CALIFORNIA WILL BE USED

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'GameNetworkingSockets': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Valve.Sockets.Native.GameNetworkingSockets_Init(IntPtr identity, StringBuilder errorMessage)
   at Valve.Sockets.Library.Initialize(StringBuilder errorMessage)
   at Valve.Sockets.Library.Initialize()
   at XLMultiplayerServer.FileServer.ServerLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Finished server initialization
Loading plugins
Finished loading plugins

Fresh winserver2019 installation with SkaterXL & .net 4.8 installed.
Works fine on home windows 10  installation, possibly looking for the DLL in the incorrect place?

**Comment by silentbaws** [comment]
Generally this is caused by not having Microsoft Visual Studio Redistributable x64 installed on the machine for the server. If anyone else encounters this issue try to install it from [here](https://aka.ms/vs/16/release/vc_redist.x64.exe)
